"""added vendor table

Revision ID: 0bcb45445033
Revises: 19654c1bd183
Create Date: 2024-01-25 16:37:51.068053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bcb45445033'
down_revision: Union[str, None] = '19654c1bd183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('vendor_name', sa.String(), nullable=True),
    sa.Column('working_city', sa.String(), nullable=True),
    sa.Column('register_address', sa.String(), nullable=True),
    sa.Column('GST_number', sa.String(), nullable=True),
    sa.Column('HSN_code', sa.String(), nullable=True),
    sa.Column('PAN_number', sa.String(), nullable=True),
    sa.Column('chapter_head', sa.String(), nullable=True),
    sa.Column('email', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('mobile_number', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('bank_details', sa.JSON(), nullable=True),
    sa.Column('document', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('vendor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor')
    # ### end Alembic commands ###
