"""added client table with alembic

Revision ID: 19654c1bd183
Revises: 1989a7f694ac
Create Date: 2024-01-25 15:04:23.117123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19654c1bd183'
down_revision: Union[str, None] = '1989a7f694ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('client_hub_name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('GST_number', sa.String(), nullable=True),
    sa.Column('email', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('mobile_number', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('HSN_code', sa.String(), nullable=True),
    sa.Column('PAN_number', sa.String(), nullable=True),
    sa.Column('bank_details', sa.JSON(), nullable=True),
    sa.Column('document', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    # ### end Alembic commands ###
