"""V2.3 : Update the product out db

Revision ID: 363b813e0a52
Revises: 8679d075998a
Create Date: 2024-05-22 16:53:02.817393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '363b813e0a52'
down_revision: Union[str, None] = '8679d075998a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory out', sa.Column('HSN_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory out', 'HSN_code')
    # ### end Alembic commands ###
