"""V1.19 : Added Product category table

Revision ID: 37a63bcbb0a6
Revises: 232b392fed64
Create Date: 2024-05-11 12:43:58.653559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37a63bcbb0a6'
down_revision: Union[str, None] = '232b392fed64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
