"""V3.5 Update the Raw data Column

Revision ID: 3888057e48e7
Revises: e12640e011b1
Create Date: 2024-06-25 12:56:44.359356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3888057e48e7'
down_revision: Union[str, None] = 'e12640e011b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
