"""V3.1 Added Sales table

Revision ID: 3e1ff943f4fe
Revises: aace8cf29e68
Create Date: 2024-06-21 12:32:05.067757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e1ff943f4fe'
down_revision: Union[str, None] = 'aace8cf29e68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('client', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('fulltime_rider', sa.Integer(), nullable=True),
    sa.Column('fulltime_order', sa.Integer(), nullable=True),
    sa.Column('partime_rider', sa.Integer(), nullable=True),
    sa.Column('partime_order', sa.Integer(), nullable=True),
    sa.Column('shift_1', sa.Integer(), nullable=True),
    sa.Column('shift_2', sa.Integer(), nullable=True),
    sa.Column('shift_3', sa.Integer(), nullable=True),
    sa.Column('shift_4', sa.Integer(), nullable=True),
    sa.Column('sales_with_gst', sa.Integer(), nullable=True),
    sa.Column('sales_without_gst', sa.Integer(), nullable=True),
    sa.Column('payout_with_gst', sa.Integer(), nullable=True),
    sa.Column('payout_without_gst', sa.Integer(), nullable=True),
    sa.Column('opening_vehicles', sa.Integer(), nullable=True),
    sa.Column('vehicles_added', sa.Integer(), nullable=True),
    sa.Column('vehicles_remove', sa.Integer(), nullable=True),
    sa.Column('active_vehicles', sa.Integer(), nullable=True),
    sa.Column('vehicle_deploy', sa.Integer(), nullable=True),
    sa.Column('vehicle_under_repair', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    # ### end Alembic commands ###
