"""V2.6 Added Weekly Field to FileInfo

Revision ID: 493c024296f3
Revises: f3c4a94f243a
Create Date: 2024-06-03 15:34:40.167939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '493c024296f3'
down_revision: Union[str, None] = 'f3c4a94f243a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fileinfo', sa.Column('weekly', sa.Boolean(), nullable=True))
    op.alter_column('inventory', 'invoice_amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.add_column('salaryinfo', sa.Column('weekly', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salaryinfo', 'weekly')
    op.alter_column('inventory', 'invoice_amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('fileinfo', 'weekly')
    # ### end Alembic commands ###
