"""V2.5 Added Total amount to Product Db

Revision ID: 5c1c771e32a6
Revises: d1c572106d82
Create Date: 2024-05-31 11:29:45.874639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c1c771e32a6'
down_revision: Union[str, None] = 'd1c572106d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('total_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'total_amount')
    # ### end Alembic commands ###
