"""added inventory data

Revision ID: 5c6b2a2a1eab
Revises: ed2f2bbb1551
Create Date: 2024-03-18 11:53:11.159512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c6b2a2a1eab'
down_revision: Union[str, None] = 'ed2f2bbb1551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('invoice_number', sa.Integer(), nullable=False),
    sa.Column('invoice_amount', sa.Integer(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('inventory_paydate', sa.Date(), nullable=True),
    sa.Column('vender', sa.String(), nullable=True),
    sa.Column('invoice_image_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('invoice_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    # ### end Alembic commands ###
