"""V1.8 Changed the dateformat of Inventory

Revision ID: 65594164a4d7
Revises: 59fef5335480
Create Date: 2024-04-10 16:01:35.576862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65594164a4d7'
down_revision: Union[str, None] = '59fef5335480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
