"""V1.10 : Added Product name in ProductOutDB

Revision ID: 83054ba7caa6
Revises: 251c5629fcf9
Create Date: 2024-04-12 18:06:46.459428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83054ba7caa6'
down_revision: Union[str, None] = '251c5629fcf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory out', sa.Column('product_name', sa.String(), nullable=True))
    op.add_column('inventory out', sa.Column('quntity', sa.Integer(), nullable=True))
    op.drop_column('inventory out', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory out', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('inventory out', 'quntity')
    op.drop_column('inventory out', 'product_name')
    # ### end Alembic commands ###
