"""V2.2 : Added GST amount and update the field

Revision ID: 8679d075998a
Revises: da068a1b0afc
Create Date: 2024-05-22 16:07:50.199100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8679d075998a'
down_revision: Union[str, None] = 'da068a1b0afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('amount_with_gst', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'amount_with_gst')
    # ### end Alembic commands ###
