"""V3.7 Update the Salary data Column

Revision ID: 8fd8a1805e21
Revises: b756856940d2
Create Date: 2024-06-25 14:59:38.216739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fd8a1805e21'
down_revision: Union[str, None] = 'b756856940d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_salary_data', sa.Column('SALARY_DAY', sa.String(), nullable=True))
    op.alter_column('weekly_salary_data', 'EXIT_DATE',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('weekly_salary_data', 'SALARY_DATE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_salary_data', sa.Column('SALARY_DATE', sa.DATE(), autoincrement=False, nullable=True))
    op.alter_column('weekly_salary_data', 'EXIT_DATE',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('weekly_salary_data', 'SALARY_DAY')
    # ### end Alembic commands ###
