"""V1.11 : Added Modification fields to inventory out table

Revision ID: 99e55a2cbbb7
Revises: 83054ba7caa6
Create Date: 2024-04-15 11:45:19.859556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99e55a2cbbb7'
down_revision: Union[str, None] = '83054ba7caa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory out', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('inventory out', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('inventory out', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory out', 'is_deleted')
    op.drop_column('inventory out', 'updated_at')
    op.drop_column('inventory out', 'created_at')
    # ### end Alembic commands ###
