"""V3.0 Correct status field

Revision ID: aace8cf29e68
Revises: bf8a759d21bf
Create Date: 2024-06-10 13:00:53.166110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aace8cf29e68'
down_revision: Union[str, None] = 'bf8a759d21bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_salary_data', sa.Column('STATUS', sa.String(), nullable=True))
    op.drop_column('weekly_salary_data', 'SATAUS')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_salary_data', sa.Column('SATAUS', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('weekly_salary_data', 'STATUS')
    # ### end Alembic commands ###
