"""V3.9 Update field name in sales

Revision ID: b313db7cb6da
Revises: d04666130690
Create Date: 2024-06-26 11:10:07.676498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b313db7cb6da'
down_revision: Union[str, None] = 'd04666130690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('total_riders', sa.Integer(), nullable=True))
    op.drop_column('sales', 'total_rider')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('total_rider', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('sales', 'total_riders')
    # ### end Alembic commands ###
