"""V1.14 Added user info in Inventory

Revision ID: b52da5ebc764
Revises: dccb1ef5cae8
Create Date: 2024-05-07 15:26:58.207193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b52da5ebc764'
down_revision: Union[str, None] = 'dccb1ef5cae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('user', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'user')
    # ### end Alembic commands ###
