"""V1.15 added hsn code and gst

Revision ID: bcc997a8648f
Revises: b52da5ebc764
Create Date: 2024-05-10 10:43:12.096193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcc997a8648f'
down_revision: Union[str, None] = 'b52da5ebc764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('HSN_code', sa.String(), nullable=True))
    op.add_column('product', sa.Column('GST', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'product', ['HSN_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_column('product', 'GST')
    op.drop_column('product', 'HSN_code')
    # ### end Alembic commands ###
