"""V3.8 Update Status field

Revision ID: d04666130690
Revises: 8fd8a1805e21
Create Date: 2024-06-25 16:17:13.827875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd04666130690'
down_revision: Union[str, None] = '8fd8a1805e21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_raw_data', sa.Column('STATUS', sa.String(), nullable=True))
    op.drop_column('weekly_raw_data', 'SATAUS')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_raw_data', sa.Column('SATAUS', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('weekly_raw_data', 'STATUS')
    # ### end Alembic commands ###
