"""V2.4 Update the Created at and Updated at in Inventory

Revision ID: d1c572106d82
Revises: 7bffe2e465bf
Create Date: 2024-05-30 12:57:02.210120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1c572106d82'
down_revision: Union[str, None] = '7bffe2e465bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
