"""V2.1 Added Product amount field

Revision ID: da068a1b0afc
Revises: f0afdaa8e737
Create Date: 2024-05-13 14:51:17.288261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da068a1b0afc'
down_revision: Union[str, None] = 'f0afdaa8e737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'amount')
    # ### end Alembic commands ###
