"""V3.3 Added Field to Sales data

Revision ID: da2f24cdc817
Revises: 9ba49d9cd5ef
Create Date: 2024-06-22 11:35:53.071284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da2f24cdc817'
down_revision: Union[str, None] = '9ba49d9cd5ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('average_rider', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('carry_forward', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('new_join_rider', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('left_rider', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'left_rider')
    op.drop_column('sales', 'new_join_rider')
    op.drop_column('sales', 'carry_forward')
    op.drop_column('sales', 'average_rider')
    # ### end Alembic commands ###
