"""V1.13 Added user info in Inventory Product

Revision ID: dccb1ef5cae8
Revises: f277cacff9ad
Create Date: 2024-05-07 14:45:39.371225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dccb1ef5cae8'
down_revision: Union[str, None] = 'f277cacff9ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('user', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'user')
    # ### end Alembic commands ###
