"""V.1.1 Update Inventory and Product table

Revision ID: eaf19e1dfc30
Revises: 5be12e96ec21
Create Date: 2024-03-28 12:55:33.132985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaf19e1dfc30'
down_revision: Union[str, None] = '5be12e96ec21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('invoice_id', sa.String(), nullable=False))
    op.alter_column('inventory', 'invoice_number',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("nextval('inventory_invoice_number_seq'::regclass)"))
    op.add_column('product', sa.Column('bike_category', sa.String(), nullable=True))
    op.add_column('product', sa.Column('color', sa.String(), nullable=True))
    op.drop_column('product', 'sub_category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('sub_category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('product', 'color')
    op.drop_column('product', 'bike_category')
    op.alter_column('inventory', 'invoice_number',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("nextval('inventory_invoice_number_seq'::regclass)"))
    op.drop_column('inventory', 'invoice_id')
    # ### end Alembic commands ###
