"""updaate the filekey

Revision ID: ed2f2bbb1551
Revises: 
Create Date: 2024-02-02 12:39:41.540179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed2f2bbb1551'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('client_hub_name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('GST_number', sa.String(), nullable=True),
    sa.Column('email', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('mobile_number', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('HSN_code', sa.String(), nullable=True),
    sa.Column('PAN_number', sa.String(), nullable=True),
    sa.Column('bank_details', sa.JSON(), nullable=True),
    sa.Column('document', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('fileinfo',
    sa.Column('filekey', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('filekey')
    )
    op.create_table('salaryinfo',
    sa.Column('filekey', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('filekey')
    )
    op.create_table('user',
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('email_id', sa.String(), nullable=True),
    sa.Column('mobile_no', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('retype_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('email_id'),
    sa.UniqueConstraint('mobile_no'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('vendor',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('vendor_name', sa.String(), nullable=True),
    sa.Column('working_city', sa.String(), nullable=True),
    sa.Column('register_address', sa.String(), nullable=True),
    sa.Column('GST_number', sa.String(), nullable=True),
    sa.Column('HSN_code', sa.String(), nullable=True),
    sa.Column('PAN_number', sa.String(), nullable=True),
    sa.Column('chapter_head', sa.String(), nullable=True),
    sa.Column('email', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('mobile_number', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('bank_details', sa.JSON(), nullable=True),
    sa.Column('document', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('vendor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor')
    op.drop_table('user')
    op.drop_table('salaryinfo')
    op.drop_table('fileinfo')
    op.drop_table('client')
    # ### end Alembic commands ###
