"""V2.6 Added name to Product out db

Revision ID: f3c4a94f243a
Revises: 5c1c771e32a6
Create Date: 2024-05-31 12:47:37.609928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3c4a94f243a'
down_revision: Union[str, None] = '5c1c771e32a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory out', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory out', 'name')
    # ### end Alembic commands ###
