"""V1.2 added one field as a forign key

Revision ID: fe0934d7c64d
Revises: c4bf767bb563
Create Date: 2024-03-29 11:47:20.540017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe0934d7c64d'
down_revision: Union[str, None] = 'c4bf767bb563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('bike_category', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('invoice_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['inventory.invoice_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_unique_constraint(None, 'inventory', ['invoice_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory', type_='unique')
    op.drop_table('product')
    # ### end Alembic commands ###
